export const FEED_TABLE_CONNECT: "FEED_TABLE_CONNECT" = "FEED_TABLE_CONNECT";
export const FEED_TABLE_DISCONNECT: "FEED_TABLE_DISCONNECT" =
  "FEED_TABLE_DISCONNECT";
export const FEED_TABLE_WS_CONNECTING: "FEED_TABLE_WS_CONNECTING" =
  "FEED_TABLE_WS_CONNECTING";
export const FEED_TABLE_WS_OPEN: "FEED_TABLE_WS_OPEN" = "FEED_TABLE_WS_OPEN";
export const FEED_TABLE_WS_CLOSE: "FEED_TABLE_WS_CLOSE" = "FEED_TABLE_WS_CLOSE";
export const FEED_TABLE_WS_ERROR: "FEED_TABLE_WS_ERROR" = "FEED_TABLE_WS_ERROR";
export const FEED_TABLE_WS_MESSAGE: "FEED_TABLE_WS_MESSAGE" =
  "FEED_TABLE_WS_MESSAGE";
