export const FEED_PROFILE_CONNECT: "FEED_PROFILE_CONNECT" =
  "FEED_PROFILE_CONNECT";
export const FEED_PROFILE_DISCONNECT: "FEED_PROFILE_DISCONNECT" =
  "FEED_PROFILE_DISCONNECT";
export const FEED_PROFILE_WS_CLOSE: "FEED_PROFILE_WS_CLOSE" =
  "FEED_PROFILE_WS_CLOSE";
export const FEED_PROFILE_WS_CONNECTING: "FEED_PROFILE_WS_CONNECTING" =
  "FEED_PROFILE_WS_CONNECTING";
export const FEED_PROFILE_WS_ERROR: "FEED_PROFILE_WS_ERROR" =
  "FEED_PROFILE_WS_ERROR";
export const FEED_PROFILE_WS_MESSAGE: "FEED_PROFILE_WS_MESSAGE" =
  "FEED_PROFILE_WS_MESSAGE";
export const FEED_PROFILE_WS_OPEN: "FEED_PROFILE_WS_OPEN" =
  "FEED_PROFILE_WS_OPEN";
